import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { User } from '../models/User.js';
import { Patient } from '../models/Patient.js';
import { Doctor } from '../models/Doctor.js';
import { Appointment } from '../models/Appointment.js';
import { Bill } from '../models/Bill.js';
import { Consultation } from '../models/Consultation.js';
import { Prescription } from '../models/Prescription.js';

dotenv.config();

// Date calculations for dynamic demo scheduling
const now = new Date();
const formatDate = (date: Date): string => {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
};

const todayDate = formatDate(now);

const yesterday = new Date(now);
yesterday.setDate(now.getDate() - 1);
const yesterdayDate = formatDate(yesterday);

const tomorrow = new Date(now);
tomorrow.setDate(now.getDate() + 1);
const tomorrowDate = formatDate(tomorrow);

const dayAfter = new Date(now);
dayAfter.setDate(now.getDate() + 2);
const dayAfterDate = formatDate(dayAfter);

// ==========================================
// 1. DEMO USERS (Admin, Doctors, Front Desk)
// ==========================================
const defaultUsers = [
  {
    name: 'Admin User',
    email: 'admin@carehub.com',
    password: 'password123',
    role: 'admin',
    status: 'active',
  },
  {
    name: 'Dr. Priya Sharma',
    email: 'doctor@carehub.com',
    password: 'password123',
    role: 'doctor',
    status: 'active',
  },
  {
    name: 'Dr. Rajesh Kulkarni',
    email: 'rajesh@carehub.com',
    password: 'password123',
    role: 'doctor',
    status: 'active',
  },
  {
    name: 'Dr. Sneha Reddy',
    email: 'sneha@carehub.com',
    password: 'password123',
    role: 'doctor',
    status: 'active',
  },
  {
    name: 'Reception Desk',
    email: 'reception@carehub.com',
    password: 'password123',
    role: 'receptionist',
    status: 'active',
  },
  {
    name: 'Kavita Nair (Front Desk)',
    email: 'kavita@carehub.com',
    password: 'password123',
    role: 'receptionist',
    status: 'active',
  },
];

// ==========================================
// 2. DOCTORS (6 Specialties)
// ==========================================
const defaultDoctors = [
  {
    doctorId: 'DOC-101',
    name: 'Dr. Priya Sharma',
    email: 'doctor@carehub.com',
    phone: '9876543210',
    specialization: 'General Medicine',
    experience: 8,
    consultationFee: 500,
    availableDays: ['Monday', 'Wednesday', 'Friday'],
    availableHours: '09:00-14:00',
    status: 'active',
  },
  {
    doctorId: 'DOC-102',
    name: 'Dr. Rajesh Kulkarni',
    email: 'rajesh@carehub.com',
    phone: '9812345678',
    specialization: 'Cardiologist',
    experience: 14,
    consultationFee: 800,
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    availableHours: '10:00-16:00',
    status: 'active',
  },
  {
    doctorId: 'DOC-103',
    name: 'Dr. Sneha Reddy',
    email: 'sneha@carehub.com',
    phone: '9833445566',
    specialization: 'Pediatrician',
    experience: 9,
    consultationFee: 600,
    availableDays: ['Monday', 'Tuesday', 'Friday'],
    availableHours: '09:00-13:00',
    status: 'active',
  },
  {
    doctorId: 'DOC-104',
    name: 'Dr. Arun Kumar',
    email: 'arun@carehub.com',
    phone: '9844112233',
    specialization: 'Orthopedics',
    experience: 12,
    consultationFee: 750,
    availableDays: ['Monday', 'Thursday', 'Saturday'],
    availableHours: '11:00-17:00',
    status: 'active',
  },
  {
    doctorId: 'DOC-105',
    name: 'Dr. Ananya Rao',
    email: 'ananya.rao@carehub.com',
    phone: '9855667788',
    specialization: 'Dermatologist',
    experience: 7,
    consultationFee: 650,
    availableDays: ['Wednesday', 'Friday', 'Saturday'],
    availableHours: '14:00-19:00',
    status: 'active',
  },
  {
    doctorId: 'DOC-106',
    name: 'Dr. Pooja Hegde',
    email: 'pooja.hegde@carehub.com',
    phone: '9866778899',
    specialization: 'Gynecologist',
    experience: 11,
    consultationFee: 700,
    availableDays: ['Monday', 'Wednesday', 'Thursday'],
    availableHours: '09:30-15:00',
    status: 'active',
  },
];

// ==========================================
// 3. PATIENTS (20 Realistic Profiles)
// ==========================================
const defaultPatients = [
  {
    patientId: 'PAT-1001',
    firstName: 'Aarav',
    lastName: 'Sharma',
    dateOfBirth: '1988-04-15',
    gender: 'male',
    phone: '9876543210',
    email: 'aarav.sharma@example.com',
    address: 'Flat 402, Lotus Heights, Bengaluru',
    bloodGroup: 'O+',
    emergencyContact: '9876543219 (Spouse)',
    status: 'active',
  },
  {
    patientId: 'PAT-1002',
    firstName: 'Ananya',
    lastName: 'Patel',
    dateOfBirth: '1995-08-22',
    gender: 'female',
    phone: '9823456781',
    email: 'ananya.p@example.com',
    address: '12 Green Avenue, Indiranagar, Bengaluru',
    bloodGroup: 'B+',
    emergencyContact: '9823456780 (Father)',
    status: 'active',
  },
  {
    patientId: 'PAT-1003',
    firstName: 'Rohan',
    lastName: 'Verma',
    dateOfBirth: '1976-11-03',
    gender: 'male',
    phone: '9711223344',
    email: 'rohan.v@example.com',
    address: 'Sector 4, HSR Layout, Bengaluru',
    bloodGroup: 'A+',
    emergencyContact: '9711223355 (Brother)',
    status: 'active',
  },
  {
    patientId: 'PAT-1004',
    firstName: 'Meera',
    lastName: 'Nair',
    dateOfBirth: '2001-02-19',
    gender: 'female',
    phone: '9944556677',
    email: 'meera.nair@example.com',
    address: '77 Lakeview Road, Koramangala, Bengaluru',
    bloodGroup: 'AB+',
    emergencyContact: '9944556688 (Mother)',
    status: 'active',
  },
  {
    patientId: 'PAT-1005',
    firstName: 'Vikram',
    lastName: 'Reddy',
    dateOfBirth: '1965-07-30',
    gender: 'male',
    phone: '9123456789',
    email: 'vikram.reddy@example.com',
    address: 'Plot 88, Whitefield, Bengaluru',
    bloodGroup: 'O-',
    emergencyContact: '9123456780 (Son)',
    status: 'active',
  },
  {
    patientId: 'PAT-1006',
    firstName: 'Sunita',
    lastName: 'Rao',
    dateOfBirth: '1979-05-14',
    gender: 'female',
    phone: '9845123456',
    email: 'sunita.rao@example.com',
    address: '45 Margosa Road, Malleshwaram, Bengaluru',
    bloodGroup: 'B+',
    emergencyContact: '9845123450 (Husband)',
    status: 'active',
  },
  {
    patientId: 'PAT-1007',
    firstName: 'Aditya',
    lastName: 'Kulkarni',
    dateOfBirth: '2018-09-12',
    gender: 'male',
    phone: '9812998877',
    email: 'aditya.parents@example.com',
    address: '22 Defence Colony, Indiranagar, Bengaluru',
    bloodGroup: 'A+',
    emergencyContact: '9812998870 (Father)',
    status: 'active',
  },
  {
    patientId: 'PAT-1008',
    firstName: 'Deepa',
    lastName: 'Krishnan',
    dateOfBirth: '1968-12-05',
    gender: 'female',
    phone: '9900112233',
    email: 'deepa.krishnan@example.com',
    address: '108 5th Phase, JP Nagar, Bengaluru',
    bloodGroup: 'O+',
    emergencyContact: '9900112244 (Daughter)',
    status: 'active',
  },
  {
    patientId: 'PAT-1009',
    firstName: 'Suresh',
    lastName: 'Nambiar',
    dateOfBirth: '1959-03-27',
    gender: 'male',
    phone: '9880223344',
    email: 'suresh.nambiar@example.com',
    address: '15 Gandhi Bazaar, Basavanagudi, Bengaluru',
    bloodGroup: 'AB-',
    emergencyContact: '9880223355 (Spouse)',
    status: 'active',
  },
  {
    patientId: 'PAT-1010',
    firstName: 'Kavya',
    lastName: 'Iyer',
    dateOfBirth: '1997-10-18',
    gender: 'female',
    phone: '9740334455',
    email: 'kavya.iyer@example.com',
    address: 'Wipro Gate 1, Electronic City Phase 1, Bengaluru',
    bloodGroup: 'B+',
    emergencyContact: '9740334466 (Sister)',
    status: 'active',
  },
  {
    patientId: 'PAT-1011',
    firstName: 'Mohammed',
    lastName: 'Farhan',
    dateOfBirth: '1984-06-25',
    gender: 'male',
    phone: '9845556677',
    email: 'm.farhan@example.com',
    address: '89 Coles Road, Frazer Town, Bengaluru',
    bloodGroup: 'A-',
    emergencyContact: '9845556688 (Brother)',
    status: 'active',
  },
  {
    patientId: 'PAT-1012',
    firstName: 'Pooja',
    lastName: 'Sundaram',
    dateOfBirth: '1992-01-14',
    gender: 'female',
    phone: '9916667788',
    email: 'pooja.sundaram@example.com',
    address: 'Green Glen Layout, Bellandur, Bengaluru',
    bloodGroup: 'O+',
    emergencyContact: '9916667799 (Husband)',
    status: 'active',
  },
  {
    patientId: 'PAT-1013',
    firstName: 'Karthik',
    lastName: 'Venkat',
    dateOfBirth: '1999-07-08',
    gender: 'male',
    phone: '9620778899',
    email: 'karthik.v@example.com',
    address: 'Spice Garden, Marathahalli, Bengaluru',
    bloodGroup: 'B+',
    emergencyContact: '9620778800 (Father)',
    status: 'active',
  },
  {
    patientId: 'PAT-1014',
    firstName: 'Ritu',
    lastName: 'Deshmukh',
    dateOfBirth: '1974-04-02',
    gender: 'female',
    phone: '9731889900',
    email: 'ritu.deshmukh@example.com',
    address: '50 2nd Stage, Banashankari, Bengaluru',
    bloodGroup: 'A+',
    emergencyContact: '9731889911 (Daughter)',
    status: 'active',
  },
  {
    patientId: 'PAT-1015',
    firstName: 'Nikhil',
    lastName: 'Hegde',
    dateOfBirth: '2012-11-20',
    gender: 'male',
    phone: '9844990011',
    email: 'hegde.family@example.com',
    address: '34 Chord Road, Rajajinagar, Bengaluru',
    bloodGroup: 'O+',
    emergencyContact: '9844990022 (Mother)',
    status: 'active',
  },
  {
    patientId: 'PAT-1016',
    firstName: 'Shweta',
    lastName: 'Joshi',
    dateOfBirth: '1990-09-09',
    gender: 'female',
    phone: '9902001122',
    email: 'shweta.joshi@example.com',
    address: 'Krishna Temple Road, Domlur, Bengaluru',
    bloodGroup: 'AB+',
    emergencyContact: '9902001133 (Husband)',
    status: 'active',
  },
  {
    patientId: 'PAT-1017',
    firstName: 'Ramesh',
    lastName: 'Goud',
    dateOfBirth: '1955-02-17',
    gender: 'male',
    phone: '9845112299',
    email: 'ramesh.goud@example.com',
    address: 'Kammanahalli Main Road, Kalyan Nagar, Bengaluru',
    bloodGroup: 'B-',
    emergencyContact: '9845112288 (Son)',
    status: 'active',
  },
  {
    patientId: 'PAT-1018',
    firstName: 'Tanvi',
    lastName: 'Agarwal',
    dateOfBirth: '2004-08-30',
    gender: 'female',
    phone: '9741223388',
    email: 'tanvi.agarwal@example.com',
    address: 'Silver County Road, Sarjapur Road, Bengaluru',
    bloodGroup: 'O+',
    emergencyContact: '9741223399 (Father)',
    status: 'active',
  },
  {
    patientId: 'PAT-1019',
    firstName: 'Arjun',
    lastName: 'Nanda',
    dateOfBirth: '1979-10-10',
    gender: 'male',
    phone: '9886334477',
    email: 'arjun.nanda@example.com',
    address: 'Godrej Woodsman Estate, Hebbal, Bengaluru',
    bloodGroup: 'A+',
    emergencyContact: '9886334488 (Spouse)',
    status: 'active',
  },
  {
    patientId: 'PAT-1020',
    firstName: 'Fatima',
    lastName: 'Khan',
    dateOfBirth: '1963-05-21',
    gender: 'female',
    phone: '9916445566',
    email: 'fatima.khan@example.com',
    address: 'Langford Gardens, Richmond Town, Bengaluru',
    bloodGroup: 'O+',
    emergencyContact: '9916445577 (Daughter)',
    status: 'inactive',
  },
];

// ==========================================
// 4. APPOINTMENTS (Today, Yesterday, Upcoming)
// ==========================================
const defaultAppointments = [
  // --- TODAY'S APPOINTMENTS (Active Queue & Tokens) ---
  {
    appointmentId: 'APT-1001',
    patientId: 'PAT-1001',
    patientName: 'Aarav Sharma',
    patientPhone: '9876543210',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    doctorSpecialization: 'General Medicine',
    date: todayDate,
    time: '09:00 AM',
    timeSlot: '09:00 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Hypertension Follow-up & BP Monitoring',
    status: 'completed',
    fee: 500,
    notes: 'Regular monthly follow-up for blood pressure',
  },
  {
    appointmentId: 'APT-1002',
    patientId: 'PAT-1002',
    patientName: 'Ananya Patel',
    patientPhone: '9823456781',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    doctorSpecialization: 'General Medicine',
    date: todayDate,
    time: '09:30 AM',
    timeSlot: '09:30 AM',
    tokenNumber: 2,
    token: 'Token #02',
    reason: 'Seasonal Viral Allergy & Sore Throat',
    status: 'completed',
    fee: 500,
    notes: 'Mild cough and throat irritation',
  },
  {
    appointmentId: 'APT-1003',
    patientId: 'PAT-1003',
    patientName: 'Rohan Verma',
    patientPhone: '9711223344',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Rajesh Kulkarni',
    doctorSpecialization: 'Cardiologist',
    date: todayDate,
    time: '10:00 AM',
    timeSlot: '10:00 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Cardiology Review & ECG Assessment',
    status: 'completed',
    fee: 800,
    notes: 'Exertion dyspnea assessment with 12-lead ECG',
  },
  {
    appointmentId: 'APT-1004',
    patientId: 'PAT-1007',
    patientName: 'Aditya Kulkarni',
    patientPhone: '9812998877',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Sneha Reddy',
    doctorSpecialization: 'Pediatrician',
    date: todayDate,
    time: '10:15 AM',
    timeSlot: '10:15 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Pediatric Fever & Pharyngitis',
    status: 'completed',
    fee: 600,
    notes: 'Fever 101F since yesterday night',
  },
  {
    appointmentId: 'APT-1005',
    patientId: 'PAT-1008',
    patientName: 'Deepa Krishnan',
    patientPhone: '9900112233',
    doctorId: 'DOC-104',
    doctorName: 'Dr. Arun Kumar',
    doctorSpecialization: 'Orthopedics',
    date: todayDate,
    time: '11:00 AM',
    timeSlot: '11:00 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Bilateral Knee Joint Pain & Stiffness',
    status: 'checked-in',
    fee: 750,
    notes: 'Patient seated in Waiting Area B',
  },
  {
    appointmentId: 'APT-1006',
    patientId: 'PAT-1005',
    patientName: 'Vikram Reddy',
    patientPhone: '9123456789',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    doctorSpecialization: 'General Medicine',
    date: todayDate,
    time: '11:30 AM',
    timeSlot: '11:30 AM',
    tokenNumber: 3,
    token: 'Token #03',
    reason: 'Type 2 Diabetes Routine Fasting Review',
    status: 'checked-in',
    fee: 500,
    notes: 'Brought recent fasting blood glucose report (148 mg/dL)',
  },
  {
    appointmentId: 'APT-1007',
    patientId: 'PAT-1010',
    patientName: 'Kavya Iyer',
    patientPhone: '9740334455',
    doctorId: 'DOC-105',
    doctorName: 'Dr. Ananya Rao',
    doctorSpecialization: 'Dermatologist',
    date: todayDate,
    time: '02:00 PM',
    timeSlot: '02:00 PM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Facial Acne & Skin Rash Evaluation',
    status: 'checked-in',
    fee: 650,
    notes: 'Checked in at Reception Counter 1',
  },
  {
    appointmentId: 'APT-1008',
    patientId: 'PAT-1004',
    patientName: 'Meera Nair',
    patientPhone: '9944556677',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    doctorSpecialization: 'General Medicine',
    date: todayDate,
    time: '02:30 PM',
    timeSlot: '02:30 PM',
    tokenNumber: 4,
    token: 'Token #04',
    reason: 'Annual Comprehensive Health Wellness',
    status: 'confirmed',
    fee: 500,
    notes: 'Token assigned; SMS reminder sent',
  },
  {
    appointmentId: 'APT-1009',
    patientId: 'PAT-1011',
    patientName: 'Mohammed Farhan',
    patientPhone: '9845556677',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    doctorSpecialization: 'General Medicine',
    date: todayDate,
    time: '03:00 PM',
    timeSlot: '03:00 PM',
    tokenNumber: 5,
    token: 'Token #05',
    reason: 'Acid Reflux & Severe Epigastric Burning',
    status: 'confirmed',
    fee: 500,
    notes: 'First time visitor; consultation scheduled',
  },
  {
    appointmentId: 'APT-1010',
    patientId: 'PAT-1012',
    patientName: 'Pooja Sundaram',
    patientPhone: '9916667788',
    doctorId: 'DOC-106',
    doctorName: 'Dr. Pooja Hegde',
    doctorSpecialization: 'Gynecologist',
    date: todayDate,
    time: '03:30 PM',
    timeSlot: '03:30 PM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: '2nd Trimester Routine Antenatal Checkup',
    status: 'confirmed',
    fee: 700,
    notes: 'Ultrasound report review',
  },
  {
    appointmentId: 'APT-1011',
    patientId: 'PAT-1013',
    patientName: 'Karthik Venkat',
    patientPhone: '9620778899',
    doctorId: 'DOC-104',
    doctorName: 'Dr. Arun Kumar',
    doctorSpecialization: 'Orthopedics',
    date: todayDate,
    time: '04:00 PM',
    timeSlot: '04:00 PM',
    tokenNumber: 2,
    token: 'Token #02',
    reason: 'Right Ankle Ligament Sprain Assessment',
    status: 'pending',
    fee: 750,
    notes: 'Awaiting phone confirmation from patient',
  },
  {
    appointmentId: 'APT-1012',
    patientId: 'PAT-1006',
    patientName: 'Sunita Rao',
    patientPhone: '9845123456',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Rajesh Kulkarni',
    doctorSpecialization: 'Cardiologist',
    date: todayDate,
    time: '04:30 PM',
    timeSlot: '04:30 PM',
    tokenNumber: 2,
    token: 'Token #02',
    reason: 'Palpitations & Thyroid Panel Review',
    status: 'cancelled',
    fee: 800,
    cancelReason: 'Patient called to reschedule for Saturday',
  },

  // --- YESTERDAY'S APPOINTMENTS (Completed History) ---
  {
    appointmentId: 'APT-1013',
    patientId: 'PAT-1009',
    patientName: 'Suresh Nambiar',
    patientPhone: '9880223344',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Rajesh Kulkarni',
    doctorSpecialization: 'Cardiologist',
    date: yesterdayDate,
    time: '10:00 AM',
    timeSlot: '10:00 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Post-Stent 6 Month Cardiology Evaluation',
    status: 'completed',
    fee: 800,
    notes: 'Stable vitals; continuation of dual antiplatelets',
  },
  {
    appointmentId: 'APT-1014',
    patientId: 'PAT-1014',
    patientName: 'Ritu Deshmukh',
    patientPhone: '9731889900',
    doctorId: 'DOC-106',
    doctorName: 'Dr. Pooja Hegde',
    doctorSpecialization: 'Gynecologist',
    date: yesterdayDate,
    time: '11:00 AM',
    timeSlot: '11:00 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Menopausal Health & Calcium Supplementation',
    status: 'completed',
    fee: 700,
    notes: 'DEXA scan advised for bone density',
  },
  {
    appointmentId: 'APT-1015',
    patientId: 'PAT-1015',
    patientName: 'Nikhil Hegde',
    patientPhone: '9844990011',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Sneha Reddy',
    doctorSpecialization: 'Pediatrician',
    date: yesterdayDate,
    time: '11:30 AM',
    timeSlot: '11:30 AM',
    tokenNumber: 2,
    token: 'Token #02',
    reason: 'Childhood Asthma Inhaler Refill & Review',
    status: 'completed',
    fee: 600,
    notes: 'Peak flow meter reading within normal limits',
  },
  {
    appointmentId: 'APT-1016',
    patientId: 'PAT-1016',
    patientName: 'Shweta Joshi',
    patientPhone: '9902001122',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    doctorSpecialization: 'General Medicine',
    date: yesterdayDate,
    time: '12:00 PM',
    timeSlot: '12:00 PM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Migraine with Visual Aura Follow-up',
    status: 'completed',
    fee: 500,
    notes: 'Prescribed prophylactic beta-blocker',
  },
  {
    appointmentId: 'APT-1017',
    patientId: 'PAT-1017',
    patientName: 'Ramesh Goud',
    patientPhone: '9845112299',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    doctorSpecialization: 'General Medicine',
    date: yesterdayDate,
    time: '02:00 PM',
    timeSlot: '02:00 PM',
    tokenNumber: 2,
    token: 'Token #02',
    reason: 'Serum Creatinine & Kidney Function Review',
    status: 'completed',
    fee: 500,
    notes: 'Advised strict low-sodium dietary protocol',
  },
  {
    appointmentId: 'APT-1018',
    patientId: 'PAT-1018',
    patientName: 'Tanvi Agarwal',
    patientPhone: '9741223388',
    doctorId: 'DOC-105',
    doctorName: 'Dr. Ananya Rao',
    doctorSpecialization: 'Dermatologist',
    date: yesterdayDate,
    time: '03:00 PM',
    timeSlot: '03:00 PM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Allergic Contact Dermatitis from Cosmetics',
    status: 'completed',
    fee: 650,
    notes: 'Topical soothing lotion and antihistamine prescribed',
  },

  // --- UPCOMING APPOINTMENTS (Tomorrow & Day After) ---
  {
    appointmentId: 'APT-1019',
    patientId: 'PAT-1019',
    patientName: 'Arjun Nanda',
    patientPhone: '9886334477',
    doctorId: 'DOC-104',
    doctorName: 'Dr. Arun Kumar',
    doctorSpecialization: 'Orthopedics',
    date: tomorrowDate,
    time: '10:00 AM',
    timeSlot: '10:00 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Lumbar Spine Spondylosis Checkup',
    status: 'confirmed',
    fee: 750,
    notes: 'Confirmed via WhatsApp notification',
  },
  {
    appointmentId: 'APT-1020',
    patientId: 'PAT-1001',
    patientName: 'Aarav Sharma',
    patientPhone: '9876543210',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Rajesh Kulkarni',
    doctorSpecialization: 'Cardiologist',
    date: tomorrowDate,
    time: '11:00 AM',
    timeSlot: '11:00 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Echocardiogram Review Consultation',
    status: 'confirmed',
    fee: 800,
    notes: 'Referred by Dr. Priya Sharma',
  },
  {
    appointmentId: 'APT-1021',
    patientId: 'PAT-1002',
    patientName: 'Ananya Patel',
    patientPhone: '9823456781',
    doctorId: 'DOC-105',
    doctorName: 'Dr. Ananya Rao',
    doctorSpecialization: 'Dermatologist',
    date: tomorrowDate,
    time: '03:00 PM',
    timeSlot: '03:00 PM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Routine Skin Glow & Hyperpigmentation',
    status: 'confirmed',
    fee: 650,
  },
  {
    appointmentId: 'APT-1022',
    patientId: 'PAT-1003',
    patientName: 'Rohan Verma',
    patientPhone: '9711223344',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    doctorSpecialization: 'General Medicine',
    date: dayAfterDate,
    time: '09:30 AM',
    timeSlot: '09:30 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Lipid Profile Blood Work Follow-up',
    status: 'confirmed',
    fee: 500,
  },
  {
    appointmentId: 'APT-1023',
    patientId: 'PAT-1007',
    patientName: 'Aditya Kulkarni',
    patientPhone: '9812998877',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Sneha Reddy',
    doctorSpecialization: 'Pediatrician',
    date: dayAfterDate,
    time: '10:00 AM',
    timeSlot: '10:00 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'MMR Booster Immunization & Wellness',
    status: 'confirmed',
    fee: 600,
  },
  {
    appointmentId: 'APT-1024',
    patientId: 'PAT-1008',
    patientName: 'Deepa Krishnan',
    patientPhone: '9900112233',
    doctorId: 'DOC-104',
    doctorName: 'Dr. Arun Kumar',
    doctorSpecialization: 'Orthopedics',
    date: dayAfterDate,
    time: '11:30 AM',
    timeSlot: '11:30 AM',
    tokenNumber: 1,
    token: 'Token #01',
    reason: 'Knee Joint Infiltration Therapy Follow-up',
    status: 'pending',
    fee: 750,
  },
];

// ==========================================
// 5. BILLING & INVOICES (16 Itemized Records)
// ==========================================
const defaultBills = [
  {
    billId: 'INV-1001',
    patientId: 'PAT-1001',
    patientName: 'Aarav Sharma',
    patientPhone: '9876543210',
    appointmentId: 'APT-1001',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    items: [
      { description: 'Doctor Consultation Fee', amount: 500, quantity: 1, unitPrice: 500 },
      { description: 'BP Check & Vitals Monitoring', amount: 150, quantity: 1, unitPrice: 150 },
    ],
    itemsSummary: 'Consultation + BP Check',
    subtotal: 650,
    discount: 50,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 600,
    amountPaid: 600,
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    transactionRef: 'UPI/20261006/98765432',
    paidAt: new Date(),
    notes: 'Payment received via Google Pay UPI',
    createdBy: 'Admin User',
  },
  {
    billId: 'INV-1002',
    patientId: 'PAT-1002',
    patientName: 'Ananya Patel',
    patientPhone: '9823456781',
    appointmentId: 'APT-1002',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    items: [
      { description: 'General Consultation Fee', amount: 500, quantity: 1, unitPrice: 500 },
      { description: 'Nebulization Therapy Session', amount: 250, quantity: 1, unitPrice: 250 },
    ],
    itemsSummary: 'Consultation + Nebulization',
    subtotal: 750,
    discount: 0,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 750,
    amountPaid: 750,
    paymentStatus: 'paid',
    paymentMethod: 'cash',
    paidAt: new Date(),
    notes: 'Settled at front counter in cash',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1003',
    patientId: 'PAT-1003',
    patientName: 'Rohan Verma',
    patientPhone: '9711223344',
    appointmentId: 'APT-1003',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Rajesh Kulkarni',
    items: [
      { description: 'Cardiology Specialist Consultation', amount: 800, quantity: 1, unitPrice: 800 },
      { description: '12-Lead Resting Digital ECG', amount: 400, quantity: 1, unitPrice: 400 },
      { description: 'Lipid Profile Comprehensive Lab Panel', amount: 750, quantity: 1, unitPrice: 750 },
    ],
    itemsSummary: 'Cardiology Consultation + ECG + Lipid Panel',
    subtotal: 1950,
    discount: 150,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 1800,
    amountPaid: 1800,
    paymentStatus: 'paid',
    paymentMethod: 'card',
    transactionRef: 'TXN-HDFC-991244',
    paidAt: new Date(),
    notes: 'Paid via Visa Platinum Credit Card',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1004',
    patientId: 'PAT-1007',
    patientName: 'Aditya Kulkarni',
    patientPhone: '9812998877',
    appointmentId: 'APT-1004',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Sneha Reddy',
    items: [
      { description: 'Pediatric Specialist Consultation', amount: 600, quantity: 1, unitPrice: 600 },
      { description: 'Rapid Streptococcal Antigen Test', amount: 350, quantity: 1, unitPrice: 350 },
    ],
    itemsSummary: 'Pediatric Consultation + Strep Test',
    subtotal: 950,
    discount: 50,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 900,
    amountPaid: 900,
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    transactionRef: 'UPI/20261006/11223344',
    paidAt: new Date(),
    notes: 'Paid via PhonePe QR at desk',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1005',
    patientId: 'PAT-1008',
    patientName: 'Deepa Krishnan',
    patientPhone: '9900112233',
    appointmentId: 'APT-1005',
    doctorId: 'DOC-104',
    doctorName: 'Dr. Arun Kumar',
    items: [
      { description: 'Orthopedic Consultation Fee', amount: 750, quantity: 1, unitPrice: 750 },
      { description: 'Digital X-Ray Bilateral Knees (AP/LAT)', amount: 900, quantity: 1, unitPrice: 900 },
    ],
    itemsSummary: 'Orthopedic Consultation + Knee X-Rays',
    subtotal: 1650,
    discount: 0,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 1650,
    amountPaid: 0,
    paymentStatus: 'pending',
    notes: 'Awaiting counter settlement after X-ray imaging',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1006',
    patientId: 'PAT-1005',
    patientName: 'Vikram Reddy',
    patientPhone: '9123456789',
    appointmentId: 'APT-1006',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    items: [
      { description: 'Diabetic Consultation & Plan', amount: 500, quantity: 1, unitPrice: 500 },
      { description: 'HbA1c Glycated Hemoglobin Test', amount: 600, quantity: 1, unitPrice: 600 },
      { description: 'Serum Creatinine & Microalbumin', amount: 450, quantity: 1, unitPrice: 450 },
    ],
    itemsSummary: 'Diabetes Consultation + HbA1c + Renal Panel',
    subtotal: 1550,
    discount: 100,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 1450,
    amountPaid: 1450,
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    transactionRef: 'UPI/20261006/77889900',
    paidAt: new Date(),
    notes: 'Paytm UPI transfer confirmed',
    createdBy: 'Admin User',
  },
  {
    billId: 'INV-1007',
    patientId: 'PAT-1010',
    patientName: 'Kavya Iyer',
    patientPhone: '9740334455',
    appointmentId: 'APT-1007',
    doctorId: 'DOC-105',
    doctorName: 'Dr. Ananya Rao',
    items: [
      { description: 'Dermatologist Specialist Consultation', amount: 650, quantity: 1, unitPrice: 650 },
      { description: 'Chemical Peel & Comedone Extraction', amount: 1200, quantity: 1, unitPrice: 1200 },
    ],
    itemsSummary: 'Dermatology Consultation + Skin Treatment',
    subtotal: 1850,
    discount: 0,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 1850,
    amountPaid: 0,
    paymentStatus: 'pending',
    notes: 'Patient currently in procedure room',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1008',
    patientId: 'PAT-1004',
    patientName: 'Meera Nair',
    patientPhone: '9944556677',
    appointmentId: 'APT-1008',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    items: [
      { description: 'Full Body Comprehensive Wellness Checkup', amount: 1500, quantity: 1, unitPrice: 1500 },
      { description: 'Complete Hemogram (CBC)', amount: 350, quantity: 1, unitPrice: 350 },
      { description: 'Serum Vitamin D3 & B12', amount: 1100, quantity: 1, unitPrice: 1100 },
    ],
    itemsSummary: 'Annual Health Check + Blood Panels',
    subtotal: 2950,
    discount: 250,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 2700,
    amountPaid: 0,
    paymentStatus: 'pending',
    notes: 'Invoice generated; awaiting payment at checkout',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1009',
    patientId: 'PAT-1009',
    patientName: 'Suresh Nambiar',
    patientPhone: '9880223344',
    appointmentId: 'APT-1013',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Rajesh Kulkarni',
    items: [
      { description: 'Cardiology Review Consultation', amount: 800, quantity: 1, unitPrice: 800 },
      { description: '2D Echocardiogram with Color Doppler', amount: 1800, quantity: 1, unitPrice: 1800 },
    ],
    itemsSummary: 'Cardiology Review + 2D Echo',
    subtotal: 2600,
    discount: 100,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 2500,
    amountPaid: 2500,
    paymentStatus: 'paid',
    paymentMethod: 'card',
    transactionRef: 'TXN-ICICI-441100',
    paidAt: yesterday,
    notes: 'Paid via ICICI POS debit card',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1010',
    patientId: 'PAT-1014',
    patientName: 'Ritu Deshmukh',
    patientPhone: '9731889900',
    appointmentId: 'APT-1014',
    doctorId: 'DOC-106',
    doctorName: 'Dr. Pooja Hegde',
    items: [
      { description: 'Gynecological Consultation Fee', amount: 700, quantity: 1, unitPrice: 700 },
      { description: 'Pap Smear Cervical Screening', amount: 650, quantity: 1, unitPrice: 650 },
    ],
    itemsSummary: 'Gynecology Consultation + Pap Smear',
    subtotal: 1350,
    discount: 0,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 1350,
    amountPaid: 1350,
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    transactionRef: 'UPI/20261005/66554433',
    paidAt: yesterday,
    notes: 'GPay UPI settlement completed',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1011',
    patientId: 'PAT-1015',
    patientName: 'Nikhil Hegde',
    patientPhone: '9844990011',
    appointmentId: 'APT-1015',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Sneha Reddy',
    items: [
      { description: 'Pediatric Asthma Consultation', amount: 600, quantity: 1, unitPrice: 600 },
      { description: 'Spirometry Lung Function Assessment', amount: 500, quantity: 1, unitPrice: 500 },
    ],
    itemsSummary: 'Pediatric Consultation + Spirometry',
    subtotal: 1100,
    discount: 50,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 1050,
    amountPaid: 1050,
    paymentStatus: 'paid',
    paymentMethod: 'cash',
    paidAt: yesterday,
    notes: 'Desk cash settlement',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1012',
    patientId: 'PAT-1016',
    patientName: 'Shweta Joshi',
    patientPhone: '9902001122',
    appointmentId: 'APT-1016',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    items: [
      { description: 'General Physician Consultation', amount: 500, quantity: 1, unitPrice: 500 },
      { description: 'Cervical Spine Mobility Examination', amount: 200, quantity: 1, unitPrice: 200 },
    ],
    itemsSummary: 'Consultation + Spine Assessment',
    subtotal: 700,
    discount: 0,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 700,
    amountPaid: 700,
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    transactionRef: 'UPI/20261005/99887711',
    paidAt: yesterday,
    notes: 'PhonePe settlement',
    createdBy: 'Admin User',
  },
  {
    billId: 'INV-1013',
    patientId: 'PAT-1017',
    patientName: 'Ramesh Goud',
    patientPhone: '9845112299',
    appointmentId: 'APT-1017',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    items: [
      { description: 'Senior Citizen Comprehensive Consultation', amount: 500, quantity: 1, unitPrice: 500 },
      { description: 'Renal Function Profile (KFT)', amount: 700, quantity: 1, unitPrice: 700 },
      { description: 'Serum Electrolytes (Na/K/Cl)', amount: 400, quantity: 1, unitPrice: 400 },
    ],
    itemsSummary: 'Senior Care Consultation + KFT + Electrolytes',
    subtotal: 1600,
    discount: 150,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 1450,
    amountPaid: 1450,
    paymentStatus: 'paid',
    paymentMethod: 'cash',
    paidAt: yesterday,
    notes: 'Senior citizen discount applied (₹150)',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1014',
    patientId: 'PAT-1018',
    patientName: 'Tanvi Agarwal',
    patientPhone: '9741223388',
    appointmentId: 'APT-1018',
    doctorId: 'DOC-105',
    doctorName: 'Dr. Ananya Rao',
    items: [
      { description: 'Dermatologist Consultation Fee', amount: 650, quantity: 1, unitPrice: 650 },
      { description: 'Skin Allergy Patch Testing Panel', amount: 850, quantity: 1, unitPrice: 850 },
    ],
    itemsSummary: 'Dermatology Consultation + Patch Test',
    subtotal: 1500,
    discount: 50,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 1450,
    amountPaid: 1450,
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    transactionRef: 'UPI/20261005/33445566',
    paidAt: yesterday,
    notes: 'Google Pay transaction',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1015',
    patientId: 'PAT-1011',
    patientName: 'Mohammed Farhan',
    patientPhone: '9845556677',
    appointmentId: 'APT-1009',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    items: [
      { description: 'Gastroenterology Consultation', amount: 500, quantity: 1, unitPrice: 500 },
      { description: 'H. Pylori Stool Antigen Rapid Test', amount: 600, quantity: 1, unitPrice: 600 },
    ],
    itemsSummary: 'Consultation + H. Pylori Test',
    subtotal: 1100,
    discount: 0,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 1100,
    amountPaid: 500,
    paymentStatus: 'partially-paid',
    paymentMethod: 'cash',
    paidAt: new Date(),
    notes: '₹500 consultation paid; ₹600 lab fee due on report collection',
    createdBy: 'Reception Desk',
  },
  {
    billId: 'INV-1016',
    patientId: 'PAT-1013',
    patientName: 'Karthik Venkat',
    patientPhone: '9620778899',
    appointmentId: 'APT-1011',
    doctorId: 'DOC-104',
    doctorName: 'Dr. Arun Kumar',
    items: [
      { description: 'Sports Injury Consultation', amount: 750, quantity: 1, unitPrice: 750 },
      { description: 'Ankle Joint Elastic Crepe Bandaging', amount: 250, quantity: 1, unitPrice: 250 },
    ],
    itemsSummary: 'Consultation + Bandaging',
    subtotal: 1000,
    discount: 0,
    taxPercent: 0,
    taxAmount: 0,
    totalAmount: 1000,
    amountPaid: 0,
    paymentStatus: 'pending',
    notes: 'Billing pending patient check-in confirmation',
    createdBy: 'Reception Desk',
  },
];

// ==========================================
// 6. CONSULTATIONS (Clinical Encounters)
// ==========================================
const defaultConsultations = [
  {
    consultationId: 'CON-1001',
    appointmentId: 'APT-1001',
    patientId: 'PAT-1001',
    patientName: 'Aarav Sharma',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    symptoms: ['Mild occipital headache in mornings', 'Fatigue', 'BP reading 142/90 mmHg'],
    diagnosis: 'Essential Hypertension Stage 1 (Mild)',
    doctorNotes: 'Advised daily 30-minute brisk walk, reduced sodium intake (<2g/day). Follow-up in 4 weeks.',
  },
  {
    consultationId: 'CON-1002',
    appointmentId: 'APT-1002',
    patientId: 'PAT-1002',
    patientName: 'Ananya Patel',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    symptoms: ['Dry throat irritation', 'Intermittent sneezing', 'Mild non-productive nocturnal cough'],
    diagnosis: 'Acute Upper Respiratory Tract Allergy / Allergic Pharyngitis',
    doctorNotes: 'Chest clear bilaterally. Prescribed antihistamine and steam inhalation twice daily for 5 days.',
  },
  {
    consultationId: 'CON-1003',
    appointmentId: 'APT-1003',
    patientId: 'PAT-1003',
    patientName: 'Rohan Verma',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Rajesh Kulkarni',
    symptoms: ['Mild retrosternal chest tightness on climbing stairs', 'Occasional shortness of breath'],
    diagnosis: 'Mild Stable Exertional Angina / Dyslipidemia',
    doctorNotes: '12-lead ECG shows non-specific ST changes. Lipid profile reveals elevated LDL (142 mg/dL). Prescribed statin.',
  },
  {
    consultationId: 'CON-1004',
    appointmentId: 'APT-1004',
    patientId: 'PAT-1007',
    patientName: 'Aditya Kulkarni',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Sneha Reddy',
    symptoms: ['Fever 101F since 24 hours', 'Reduced appetite', 'Erythematous throat'],
    diagnosis: 'Acute Pediatric Viral Pharyngitis',
    doctorNotes: 'No exudates seen in tonsils. Paracetamol antipyretic prescribed. Hydration with warm fluids encouraged.',
  },
  {
    consultationId: 'CON-1005',
    appointmentId: 'APT-1013',
    patientId: 'PAT-1009',
    patientName: 'Suresh Nambiar',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Rajesh Kulkarni',
    symptoms: ['Routine 6-month post-PCI follow-up', 'Good exercise tolerance', 'No anginal complaints'],
    diagnosis: 'Post-Percutaneous Coronary Intervention (PCI) — Clinically Stable',
    doctorNotes: 'Heart sounds normal. Pulse 72 bpm regular. Continue dual antiplatelet therapy (Aspirin + Clopidogrel).',
  },
  {
    consultationId: 'CON-1006',
    appointmentId: 'APT-1015',
    patientId: 'PAT-1015',
    patientName: 'Nikhil Hegde',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Sneha Reddy',
    symptoms: ['Cough triggered by cold morning air', 'Occasional wheezing after sports'],
    diagnosis: 'Childhood Bronchial Asthma (Intermittent)',
    doctorNotes: 'Chest shows faint expiratory wheeze. Inhaler technique corrected with spacer device. Follow-up after winter.',
  },
];

// ==========================================
// 7. PRESCRIPTIONS (Realistic Clinical Rx)
// ==========================================
const defaultPrescriptions = [
  {
    prescriptionId: 'RX-1001',
    consultationId: 'CON-1001',
    appointmentId: 'APT-1001',
    patientId: 'PAT-1001',
    patientName: 'Aarav Sharma',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    medicines: [
      {
        name: 'Telmisartan 40mg',
        dosage: '1 tablet',
        frequency: 'Once daily in the morning',
        duration: '30 days',
        instructions: 'Take after breakfast with water. Monitor BP weekly.',
      },
      {
        name: 'Amlodipine 5mg',
        dosage: '1 tablet',
        frequency: 'Once daily at night',
        duration: '30 days',
        instructions: 'Take after dinner. Report if any ankle swelling occurs.',
      },
    ],
    notes: 'Low salt diet (< 2 grams/day), 30 mins brisk walking daily. Review in 1 month.',
  },
  {
    prescriptionId: 'RX-1002',
    consultationId: 'CON-1002',
    appointmentId: 'APT-1002',
    patientId: 'PAT-1002',
    patientName: 'Ananya Patel',
    doctorId: 'DOC-101',
    doctorName: 'Dr. Priya Sharma',
    medicines: [
      {
        name: 'Levocetirizine + Montelukast (5mg/10mg)',
        dosage: '1 tablet',
        frequency: 'Once daily at bedtime',
        duration: '7 days',
        instructions: 'May cause mild drowsiness. Avoid alcohol.',
      },
      {
        name: 'Warm Saline Gargles',
        dosage: 'Gargle 100ml',
        frequency: 'Thrice daily',
        duration: '5 days',
        instructions: 'Perform after meals with lukewarm water.',
      },
      {
        name: 'Paracetamol 650mg',
        dosage: '1 tablet',
        frequency: 'Twice daily SOS',
        duration: '3 days',
        instructions: 'Take only if fever or headache exceeds comfort level.',
      },
    ],
    notes: 'Drink plenty of warm liquids. Avoid cold foods/beverages.',
  },
  {
    prescriptionId: 'RX-1003',
    consultationId: 'CON-1003',
    appointmentId: 'APT-1003',
    patientId: 'PAT-1003',
    patientName: 'Rohan Verma',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Rajesh Kulkarni',
    medicines: [
      {
        name: 'Atorvastatin 20mg',
        dosage: '1 tablet',
        frequency: 'Once daily at bedtime',
        duration: '60 days',
        instructions: 'Take post dinner. Essential for cholesterol plaque stabilization.',
      },
      {
        name: 'Aspirin 75mg (Enteric Coated)',
        dosage: '1 tablet',
        frequency: 'Once daily after lunch',
        duration: '60 days',
        instructions: 'Always take after food. Do not chew or crush.',
      },
      {
        name: 'Sorbitrate 5mg (Sublingual)',
        dosage: '1 tablet',
        frequency: 'SOS (as needed)',
        duration: '15 days',
        instructions: 'Place under tongue immediately if sudden severe chest heaviness occurs.',
      },
    ],
    notes: 'Undergo TMT (Treadmill Test) next week. Maintain strict low-fat cardiac diet.',
  },
  {
    prescriptionId: 'RX-1004',
    consultationId: 'CON-1004',
    appointmentId: 'APT-1004',
    patientId: 'PAT-1007',
    patientName: 'Aditya Kulkarni',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Sneha Reddy',
    medicines: [
      {
        name: 'Paracetamol 250mg/5ml Syrup',
        dosage: '5 ml',
        frequency: 'Every 6 hours as needed',
        duration: '3 days',
        instructions: 'Administer only if body temperature exceeds 99.5°F.',
      },
      {
        name: 'Cetirizine 5mg/5ml Syrup',
        dosage: '2.5 ml',
        frequency: 'Once daily at bedtime',
        duration: '5 days',
        instructions: 'For runny nose and sneezing relief.',
      },
    ],
    notes: 'Light home-cooked meals (khichdi, soups). Sponging with lukewarm water if fever spikes.',
  },
  {
    prescriptionId: 'RX-1005',
    consultationId: 'CON-1005',
    appointmentId: 'APT-1013',
    patientId: 'PAT-1009',
    patientName: 'Suresh Nambiar',
    doctorId: 'DOC-102',
    doctorName: 'Dr. Rajesh Kulkarni',
    medicines: [
      {
        name: 'Clopidogrel 75mg + Aspirin 75mg',
        dosage: '1 tablet',
        frequency: 'Once daily after breakfast',
        duration: '90 days',
        instructions: 'Strict adherence required post-stent implant. Do not miss any doses.',
      },
      {
        name: 'Rosuvastatin 10mg',
        dosage: '1 tablet',
        frequency: 'Once daily at night',
        duration: '90 days',
        instructions: 'Lipid stabilization therapy.',
      },
      {
        name: 'Metoprolol Succinate 25mg ER',
        dosage: '1 tablet',
        frequency: 'Once daily in the morning',
        duration: '90 days',
        instructions: 'Cardioprotective beta-blocker.',
      },
    ],
    notes: 'Regular morning walks. Check BP and pulse bi-weekly. Review after 3 months.',
  },
  {
    prescriptionId: 'RX-1006',
    consultationId: 'CON-1006',
    appointmentId: 'APT-1015',
    patientId: 'PAT-1015',
    patientName: 'Nikhil Hegde',
    doctorId: 'DOC-103',
    doctorName: 'Dr. Sneha Reddy',
    medicines: [
      {
        name: 'Budesonide 100mcg Inhaler',
        dosage: '1 puff',
        frequency: 'Twice daily (Morning & Evening)',
        duration: '30 days',
        instructions: 'Rinse mouth with water thoroughly after each inhalation.',
      },
      {
        name: 'Levosalbutamol 50mcg Inhaler',
        dosage: '1-2 puffs',
        frequency: 'SOS (as needed for wheezing)',
        duration: '30 days',
        instructions: 'Rescue inhaler. Use 10 minutes prior to vigorous sports.',
      },
    ],
    notes: 'Always use with spacer mask. Keep emergency rescue inhaler in school bag.',
  },
];

// ==========================================
// 8. DATABASE SEED EXECUTION
// ==========================================
const seedDatabase = async () => {
  const uri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/carehub';
  try {
    console.log('🔄 Connecting to database...');
    await mongoose.connect(uri);
    console.log('✅ Connected to MongoDB.');

    // 1. Users
    console.log('👥 Seeding Users...');
    await User.deleteMany({
      email: { $in: defaultUsers.map((u) => u.email) },
    });
    for (const u of defaultUsers) {
      await User.create(u);
    }

    // 2. Doctors
    console.log('🩺 Seeding Doctors...');
    await Doctor.deleteMany({
      doctorId: { $in: defaultDoctors.map((d) => d.doctorId) },
    });
    for (const d of defaultDoctors) {
      await Doctor.create(d);
    }

    // 3. Patients
    console.log('🧑‍🤝‍🧑 Seeding Patients...');
    await Patient.deleteMany({
      patientId: { $in: defaultPatients.map((p) => p.patientId) },
    });
    for (const p of defaultPatients) {
      await Patient.create(p);
    }

    // 4. Appointments
    console.log('📅 Seeding Appointments...');
    await Appointment.deleteMany({
      appointmentId: { $in: defaultAppointments.map((a) => a.appointmentId) },
    });
    for (const a of defaultAppointments) {
      await Appointment.create(a);
    }

    // 5. Bills & Invoices
    console.log('🧾 Seeding Bills & Invoices...');
    await Bill.deleteMany({
      billId: { $in: defaultBills.map((b) => b.billId) },
    });
    for (const b of defaultBills) {
      await Bill.create(b);
    }

    // 6. Consultations
    console.log('📝 Seeding Clinical Consultations...');
    await Consultation.deleteMany({
      consultationId: { $in: defaultConsultations.map((c) => c.consultationId) },
    });
    for (const c of defaultConsultations) {
      await Consultation.create(c);
    }

    // 7. Prescriptions
    console.log('💊 Seeding Prescriptions...');
    await Prescription.deleteMany({
      prescriptionId: { $in: defaultPrescriptions.map((p) => p.prescriptionId) },
    });
    for (const p of defaultPrescriptions) {
      await Prescription.create(p);
    }

    console.log('\n============================================================');
    console.log('🎉 CAREHUB EXPANDED DEMO DATA SEEDED SUCCESSFULLY!');
    console.log('============================================================');
    console.log('🔑 TEST LOGIN CREDENTIALS:');
    console.log('   👑 Admin:        admin@carehub.com     / password123');
    console.log('   🩺 Doctor (Gen): doctor@carehub.com    / password123 (Dr. Priya Sharma)');
    console.log('   🩺 Doctor (Card):rajesh@carehub.com    / password123 (Dr. Rajesh Kulkarni)');
    console.log('   🩺 Doctor (Ped): sneha@carehub.com     / password123 (Dr. Sneha Reddy)');
    console.log('   📋 Receptionist: reception@carehub.com / password123');
    console.log('------------------------------------------------------------');
    console.log(`🩺 Doctors:      6 specialties (DOC-101 to DOC-106)`);
    console.log(`👥 Patients:     20 diverse profiles (PAT-1001 to PAT-1020)`);
    console.log(`📅 Appointments: 24 scheduled appointments:`);
    console.log(`                 • 12 TODAY (${todayDate}) with active live queue & tokens`);
    console.log(`                 • 6 YESTERDAY (${yesterdayDate}) historical visits`);
    console.log(`                 • 6 UPCOMING (${tomorrowDate} & ${dayAfterDate})`);
    console.log(`🧾 Invoices:     16 itemized bills (INV-1001 to INV-1016)`);
    console.log(`                 • ₹22,000+ total revenue metrics`);
    console.log(`                 • Paid (UPI, Card, Cash) & Pending counter dues`);
    console.log(`📝 Consultations: 6 clinical encounters with diagnostic notes`);
    console.log(`💊 Prescriptions: 6 multi-drug Rx with dosage, timing & print preview`);
    console.log('============================================================\n');

    process.exit(0);
  } catch (error: any) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
};

seedDatabase();
